### ISSUE TITLE
bug with this example in protein group visualization

### ISSUE THREAD

**Issue by ypriverol** [PRIDE-Toolsuite/pride-inspector#48]
Here you can find the file that was tested:
http://www.ebi.ac.uk/~yperez/111405_075_Mix_1_01.mzid

**Comment by julianu** [comment]
the bug is partially fixed with commit 86003fa:
it is possible to use the visualization without working PSM scores for now

The actual problem is, that the scores are not accessible with the "controller.getPeptideByIndex(proteinID, peptideID).getSpectrumIdentification().getScore().getCvTermReferenceWithValues()", nor are they listed when calling "controller.getAvailablePeptideLevelScores()"

There are some more issues with this file:
there are null-pointer exceptions when calling "controller.getPeptideByIndex(proteinID, peptideID).getSpectrumIdentification().getSequence()" and "...getModifications"(), though calling "controller.getPeptideByIndex(proteinID, peptideID).getSequence()" and the respective "getModifications()" does work.

**Comment by ypriverol** [comment]
Can you check Why? if is a wrong reporting of something..

**Comment by julianu** [comment]
I do not know whether the issues with the score and sequences are linked, but:
- I have the same issues with the scores in other files (the PIA upload into PRIDE)
- the scores are also not shown in the protein or peptide tab

I close this issue.
@Yasset: maybe open a new one concerning the scores

**Comment by ypriverol** [comment]
Are this scores included in PRIDE utilities @julianu because we are only supporting the scores that are included in PRIDE utilitiies. We should include the PIA scores inside PRIDE Utilities and PIA also as search engine. I can open an issue in PRIDE Utilities if you want.

**Comment by julianu** [comment]
The PIA scores are not in PRIDE utilities (but in psi-obo), would be good if you could add them.
The "ProteinLynx:Ladder Score" (which is used in your example file) is in the utilities, though with an typo in its name (MS_PROTEIN_LYNC_SCORE).

**Comment by ypriverol** [comment]
I will try to include the PIA socres in ms-data core -api can you add here all the scores you are using.

**Comment by julianu** [comment]
For the protein score I use MS:1002394 (name: PIA:protein score).
The only other score that right now gets calculated is the MS:1002355 (name: PSM-level FDRScore). otherwise PIA should be able to use all scores in the PSI-OBO.

**Comment by ypriverol** [comment]
We are using the pride-utilities library http://github.com/PRIDE-Utilitites/pride-utilities to keep track to all the scores in different search engines.

**Comment by ypriverol** [comment]
@julianu if you are ok with this I will close this issue.
