### ISSUE TITLE
Pride inspector is not searching internet database, probably not connecting

### ISSUE THREAD

**Issue by rafaeltiveron** [PRIDE-Toolsuite/pride-inspector#68]
Not searching. My linux firewall is disabled. I've tested in Windows. Same result.

**Comment by lars-kolbowski** [comment]
same issue. Tried both from Windows Server and Ubuntu. No search results get returned.

**Comment by colin-combe** [comment]
yep, same

**Comment by ypriverol** [comment]
Thanks @rafaeltiveron @lars-kolbowski and @colin-combe for reporting this issue. the problem was related to the problem was related to https change in the EBI. It has been resolved in the current version and I just deploy a new version 2.5.4 (http://ftp.pride.ebi.ac.uk/pride/resources/tools/inspector/latest/desktop/pride-inspector.zip). Please let us know if you found more issues.
